---
- hosts: all
  roles:
  - wordpress
  vars:
    wordpress_installs:
      - name: wordpress
        dbname: wordpress
        dbuser: wordpress
        dbpass: 'heCrE7d2KEs'
        dbhost: localhost
        path: /var/www/html/
        owner: root
        group: apache
        url: 'http://grimlock-wordpress.redhatgov.io'
        title: wordpress
        admin_name: admin
        admin_email: root@localhost.localdomain
        admin_password: 'tuFr8=aPra@a'
        themes:
          - name: twentytwelve
            activate: true
          - name: twentythirteen
        plugins:
          - name: contact-form-7
            activate: false
#          - name: simple-fields
        users: {}
        options: []
        queries: []
  environment:
    PATH: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin

